name: Security Scans

permissions:
  contents: read
  security-events: write

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

jobs:
    scan:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Generate Trivy Vulnerability Report
              uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 # v0.36.0
              with:
                scan-type: "fs"
                scan-ref: .
                format: 'sarif'
                output: 'trivy-results.sarif'
                exit-code: 0

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@f52b05f4acaaa234e44466e66d29050e135ea9ef # v4.36.0
              with:
                sarif_file: 'trivy-results.sarif'

            - name: Fail build on High/Criticial Vulnerabilities
              uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 # v0.36.0
              with:
                scan-type: "fs"
                scan-ref: .
                format: table
                severity: HIGH,CRITICAL
                ignore-unfixed: true
                exit-code: 1
                # On a subsequent call to the action we know trivy is already installed so can skip this
                skip-setup-trivy: true